# Pandas Deep-Dive

#### 1. Import Pandas package under the alias pd and Numpy under the alias np.

In [1]:
# your code here
import numpy as np 
import pandas as pd 
from sqlalchemy import create_engine

In [2]:
driver   = 'mysql+pymysql:'
user     = 'data-students'
password = 'iR0nH@cK-D4T4B4S3'
ip       = '34.65.10.136'
database = 'appleStore'
connection_string = f'{driver}//{user}:{password}@{ip}/{database}'
print(connection_string)

mysql+pymysql://data-students:iR0nH@cK-D4T4B4S3@34.65.10.136/appleStore


#### 2. Define a variable called `path` that contains the path to the csv file you downloaded. If you are reading the data from Ironhack's database, define the variables needed to create the connection with the database. 

In [4]:
# your code here
engine = create_engine(connection_string)
print(engine)

Engine(mysql+pymysql://data-students:***@34.65.10.136/appleStore)


#### 3. Using the pandas, read the data either from the downladed file or the database. 

Assign the returned value to a variable called `data`.

In [6]:
# your code here
data = pd.read_sql('SELECT * FROM data;', engine)

#### 4. Print the first 5 rows of `data` to see what the data look like.

A data analyst usually does this to have a general understanding about what the data look like before digging deep.

In [9]:
# your code here
data.head()

id                                         track_name  size_bytes  \
0  281656475                                    PAC-MAN Premium   100788224   
1  281796108                          Evernote - stay organized   158578688   
2  281940292    WeatherBug - Local Weather, Radar, Maps, Alerts   100524032   
3  282614216  eBay: Best App to Buy, Sell, Save! Online Shop...   128512000   
4  282935706                                              Bible    92774400   

  price  rating_count_tot  rating_count_ver user_rating   prime_genre  
0  3.99             21292                26           4         Games  
1     0            161065                26           4  Productivity  
2     0            188583              2822         3.5       Weather  
3     0            262241               649           4      Shopping  
4     0            985920              5320         4.5     Reference

#### 5. Print the summary of the data.

In [19]:
# your code here
pd.set_option('display.float_format', lambda x: '%.2f' % x)
data.describe()

id    size_bytes  rating_count_tot  rating_count_ver
count       7197.00       7197.00           7197.00           7197.00
mean   863130997.45  199134453.83          12892.91            460.37
std    271236755.89  359206913.54          75739.41           3920.46
min    281656475.00     589824.00              0.00              0.00
25%    600093661.00   46922752.00             28.00              1.00
50%    978148241.00   97153024.00            300.00             23.00
75%   1082309664.00  181924864.00           2793.00            140.00
max   1188375727.00 4025969664.00        2974676.00         177050.00

#### 6. Print the number of columns in the data.

In [17]:
# your code here
print('the number of columns is: {}'.format(data.shape[1]))

the number of columns is: 8


#### 7. Print all column names.

In [28]:
# your code here
data.columns

Index(['id', 'track_name', 'size_bytes', 'price', 'rating_count_tot',
       'rating_count_ver', 'user_rating', 'prime_genre'],
      dtype='object')

In [29]:
# another way to do it
data.columns.values.tolist()

['id',
 'track_name',
 'size_bytes',
 'price',
 'rating_count_tot',
 'rating_count_ver',
 'user_rating',
 'prime_genre']

#### 8.- Now that we have a general understanding of the data, we'll start working on the challenge questions. How many apps are there in the data source? Print the number of observations of the data.

**Hint**: Your code should return the number 7197.

In [37]:
# your code here
data['track_name'].count()

7197

#### 9. What is the average rating of all apps? 

First, read the `user_rating` column into a varialbe named `user_rating`.

In [51]:
# your code here
data.dtypes

id                   int64
track_name          object
size_bytes           int64
price               object
rating_count_tot     int64
rating_count_ver     int64
user_rating         object
prime_genre         object
dtype: object

In [137]:
# user rating is an object, that's why I can't get its average, let's change it to float.
data['user_rating'] = pd.to_numeric(data['user_rating'])

Now you can calculate the average of the `user_rating` data.

**Hint**: Your code should return 3.526955675976101.

In [139]:
# your code here
data['user_rating'].mean()

3.526955675976101

#### 10. How many apps have an average rating no less than 4?

First, filter `user_rating` where its value >= 4. 

Assign the filtered dataframe to a new variable called `user_rating_high`.

In [60]:
# your code here
user_rating_high = user_rating.loc[user_rating>=4]
user_rating_high

0      4.00
1      4.00
3      4.00
4      4.50
5      4.00
       ... 
7192   4.50
7193   4.50
7194   4.50
7195   4.50
7196   5.00
Name: user_rating, Length: 4781, dtype: float64

Now obtain the length of `user_rating_high` which should return 4781.

In [61]:
# your code here
len(user_rating_high)

4781

#### 11. How many genres are there in total for all the apps?

Define a new variable named `genres` that contains the `prime_genre` column of `data`. Google for how to obtain unique values of a dataframe column. 

In [69]:
# your code here
genres = data['prime_genre'].unique()
genres

array(['Games', 'Productivity', 'Weather', 'Shopping', 'Reference',
       'Finance', 'Music', 'Utilities', 'Travel', 'Social Networking',
       'Sports', 'Business', 'Health & Fitness', 'Entertainment',
       'Photo & Video', 'Navigation', 'Education', 'Lifestyle',
       'Food & Drink', 'News', 'Book', 'Medical', 'Catalogs'],
      dtype=object)

Print the length of the unique values of `genres`. Your code should return 23.

In [70]:
# your code here
len(genres)

23

#### 12. What are the top 3 genres that have the most number of apps?

What you want to do is to count the number of occurrences of each unique genre values. Because you already know how to obtain the unique genre values, you can of course count the # of apps of each genre one by one. However, Pandas has a convient function to let you count all values of a dataframe column with a single command. Google for "pandas count values" to find the solution. Your code should return the following:

```
Games            3862
Entertainment     535
Education         453
Name: prime_genre, dtype: int64
```

In [78]:
# your code here
top3 = data['prime_genre'].value_counts().head(3)
top3

Games            3862
Entertainment     535
Education         453
Name: prime_genre, dtype: int64

#### 13. Which genre is most likely to contain free apps?

First, filter `data` where the price is 0.00. Assign the filtered data to a new variable called `free_apps`. Then count the values in `free_apps`. Your code should return:

```
Games                2257
Entertainment         334
Photo & Video         167
Social Networking     143
Education             132
Shopping              121
Utilities             109
Lifestyle              94
Finance                84
Sports                 79
Health & Fitness       76
Music                  67
Book                   66
Productivity           62
News                   58
Travel                 56
Food & Drink           43
Weather                31
Navigation             20
Reference              20
Business               20
Catalogs                9
Medical                 8
Name: prime_genre, dtype: int64
```

In [140]:
# your code here
data['price'] = pd.to_numeric(data['price'])
free_apps = data[data['user_rating']==0]
count_free_apps = data["prime_genre"].value_counts()
count_free_apps

Games                3862
Entertainment         535
Education             453
Photo & Video         349
Utilities             248
Health & Fitness      180
Productivity          178
Social Networking     167
Lifestyle             144
Music                 138
Shopping              122
Sports                114
Book                  112
Finance               104
Travel                 81
News                   75
Weather                72
Reference              64
Food & Drink           63
Business               57
Navigation             46
Medical                23
Catalogs               10
Name: prime_genre, dtype: int64

#### 14. Now you can calculate the proportion of the free apps in each genre based on the value counts you obtained in the previous two steps. 

Challenge yourself by achieving that with one line of code. The output should look like:

```
Shopping             0.991803
Catalogs             0.900000
Social Networking    0.856287
Finance              0.807692
News                 0.773333
Sports               0.692982
Travel               0.691358
Food & Drink         0.682540
Lifestyle            0.652778
Entertainment        0.624299
Book                 0.589286
Games                0.584412
Music                0.485507
Photo & Video        0.478510
Utilities            0.439516
Navigation           0.434783
Weather              0.430556
Health & Fitness     0.422222
Business             0.350877
Productivity         0.348315
Medical              0.347826
Reference            0.312500
Education            0.291391
Name: prime_genre, dtype: float64
```

The numbers are interesting, aren't they?

In [145]:
count_free_apps

Games                462
Education             66
Entertainment         64
Book                  47
Finance               33
Social Networking     33
Lifestyle             31
Utilities             29
Photo & Video         24
Health & Fitness      21
Shopping              16
News                  15
Navigation            15
Sports                13
Food & Drink          11
Reference             11
Travel                10
Weather                6
Productivity           6
Catalogs               5
Music                  4
Business               4
Medical                3
Name: prime_genre, dtype: int64

In [146]:
# your code here
count_apps              = data['prime_genre'].value_counts()
count_free_apps         = free_apps['prime_genre'].value_counts()
count_free_apps_percent = count_free_apps/count_apps
count_free_apps_percent.sort_values(ascending=False)

Catalogs            0.50
Book                0.42
Navigation          0.33
Finance             0.32
Lifestyle           0.22
News                0.20
Social Networking   0.20
Food & Drink        0.17
Reference           0.17
Education           0.15
Shopping            0.13
Medical             0.13
Travel              0.12
Games               0.12
Entertainment       0.12
Utilities           0.12
Health & Fitness    0.12
Sports              0.11
Weather             0.08
Business            0.07
Photo & Video       0.07
Productivity        0.03
Music               0.03
Name: prime_genre, dtype: float64

#### 15. If a developer tries to make money by developing and selling Apple Store apps, in which genre should s/he develop the apps? Please assume all apps cost the same amount of time and expense to develop.

We will leave this question to you. There are several way to solve it. Ideally your output should look like below:

```
    average_price              genre
21       8.776087            Medical
11       5.116316           Business
4        4.836875          Reference
6        4.835435              Music
1        4.330562       Productivity
15       4.124783         Navigation
16       4.028234          Education
12       1.916444   Health & Fitness
20       1.790536               Book
7        1.647621          Utilities
2        1.605417            Weather
18       1.552381       Food & Drink
14       1.473295      Photo & Video
0        1.432923              Games
8        1.120370             Travel
10       0.953070             Sports
13       0.889701      Entertainment
17       0.885417          Lifestyle
22       0.799000           Catalogs
19       0.517733               News
5        0.421154            Finance
9        0.339880  Social Networking
3        0.016311           Shopping
```

In [147]:
# your code here
avg_price = data.groupby('prime_genre').mean()['price'].sort_values(ascending= False)
avg_price

prime_genre
Medical             8.78
Business            5.12
Reference           4.84
Music               4.84
Productivity        4.33
Navigation          4.12
Education           4.03
Health & Fitness    1.92
Book                1.79
Utilities           1.65
Weather             1.61
Food & Drink        1.55
Photo & Video       1.47
Games               1.43
Travel              1.12
Sports              0.95
Entertainment       0.89
Lifestyle           0.89
Catalogs            0.80
News                0.52
Finance             0.42
Social Networking   0.34
Shopping            0.02
Name: price, dtype: float64